version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - app-network

  db:
    image: keinos/sqlite3:latest
    volumes:
      - sqlite-db:/data
    networks:
      - app-network

volumes:
  sqlite-db:

networks:
  app-network: