name: Lint
on:
  pull_request:
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancel all previous workflow runs for the same branch that have not yet completed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Setup Yarn
        uses: threeal/setup-yarn-action@v2.0.0

      - name: Install dependencies
        run: yarn install

      - name: Lint with ESLint
        run: yarn lint --format json --output-file eslint_report.json
        continue-on-error: true

      - name: Show Linting Results
        uses: ataylorme/eslint-annotate-action@3.0.0
        if: always()
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          report-json: 'eslint_report.json'